production:
  server: "https://pubpubhero.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: 99a9b7bf100935a05e350932ec5fde9b0f8cc5dccdbb0d64cea065d8ead42047
  signature_expiration: 3600 # one day